name: sdk_xyo_flutter
description: XYO SDK for Flutter Projects
version: 0.2.3
homepage: https://github.com/XYOracleNetwork/sdk-xyo-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.1
  mutex: ^3.0.0
  retry: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: network.xyo.sdk_xyo_flutter
        pluginClass: SdkXyoFlutterPlugin
      ios:
        pluginClass: SdkXyoFlutterPlugin

module:
  androidX: true
  androidPackage: network.xyo.sdk_xyo_flutter
  iosBundleIdentifier: network.xyo.sdkxyoflutter
